### ISSUE TITLE
Not working on schedule event

### ISSUE THREAD

**Issue by dreinon** [release-drafter/release-drafter#1148]
I get the following output running release-drafter in a schedule:

```js
Warning: Invalid config file
{
  name: 'event',
  id: '2361809012',
  stack: 'Error: context.repo() is not supported for this webhook event.\n' +
    '    at Context.repo (/home/runner/work/_actions/release-drafter/release-drafter/v5/dist/index.js:114661:19)\n' +
    '    at Context.config (/home/runner/work/_actions/release-drafter/release-drafter/v5/dist/index.js:114766:29)\n' +
    '    at getConfig (/home/runner/work/_actions/release-drafter/release-drafter/v5/dist/index.js:141549:38)\n' +
    '    at drafter (/home/runner/work/_actions/release-drafter/release-drafter/v5/dist/index.js:141186:26)\n' +
    '    at /home/runner/work/_actions/release-drafter/release-drafter/v5/dist/index.js:8629:14\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n' +
    '    at async Promise.all (index 0)',
  type: 'Error'
}
Error: Invalid config file
```

**Comment by dreinon** [comment]
The issue is with this line: https://github.com/release-drafter/release-drafter/blob/master/lib/schema.js#L15

**Comment by dreinon** [comment]
It might get solved replacing the current call with:

```js
try{
  const defaultBranch = _.get( 
     context, 
     'payload.repository.default_branch', 
     'master' 
   )
}
catch(){
  const defaultBranch = 'master';
}
```

**Comment by jetersen** [comment]
This is not the issue
https://github.com/release-drafter/release-drafter/blob/58fb030b397249d95d8b57be331b5c1e410eb312/lib/schema.js?rgh-link-date=2022-05-21T07%3A09%3A46Z#L15

This is already safely trying retrieve the value and default to master. Check out [lodash get](https://lodash.com/docs/#get)

The stack trace you provided clearly shows the issue is with retrieve the config and not the default config.

This is coming from probot: https://github.com/probot/probot/blob/3a7bbb2e1ab95b7a592bbbbac78fd6f175cd85b9/src/context.ts#L100-L104

My answer is do not use schedule events.

**Comment by dreinon** [comment]
Right, it totally looks like it comes from probot. But I think release-drafter could be able to workaround that restriction.
Lodash get is safe regarding to "Cannot read property of undefined" errors, but I don't think it is able to handle custom errors like the one thrown by probot, therefore the trycatch would make sense for this case.

**Comment by dreinon** [comment]
As seen [here](https://github.com/release-drafter/release-drafter/search?l=JavaScript&q=repository), the repository property of context is only accessed twice, in [lib/log.js](https://github.com/release-drafter/release-drafter/blob/58fb030b397249d95d8b57be331b5c1e410eb312/lib/log.js#L2) and in [lib/schema.js](https://github.com/release-drafter/release-drafter/blob/master/lib/schema.js#L15), where only the default_branch and the full_name props of repository are needed.

For schedule events, as seen in [github docs](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule), there is not an event payload, but it mentions that the default_branch is the **GITHUB_REF** environment variable, and the full_name can always be found at the **GITHUB_REPOSITORY** env variable, as stated here https://docs.github.com/en/actions/learn-github-actions/environment-variables#default-environment-variables.

Would it be possible to get the repository name in `lib/log.js` with the **GITHUB_REPOSITORY** env variable, and to have a conditional depending on the **GITHUB_EVENT_NAME** env variable, that when it is schedule, it gets the default branch from the **GITHUB_REF** env variable?

**Comment by jetersen** [comment]
Again both log and schema are safely checking the repository property and are not the issue.
Both are conditionally checking the property.

The issue remains with probot.

**Comment by dreinon** [comment]
@jetersen Right. My proposal is not to use probot context to get these two variables, and instead, using environment variables. Probot won't raise the error if we don't use the feature that throws the error. But maybe (most probably), I'm missing something, you have, for sure, more experience with the repo.

**Comment by robbruce** [comment]
@jetersen @dreinon - we are facing the same issue, we're currently using release drafter on a weekly schedule whereby (although yes this quite hacky) we run once and capture the output, then we run release drafter again as a second step and set publish to true if release only contain changes by dependabot

**Comment by cchanche** [comment]
Probot was removed (replaced) in [v7](https://github.com/release-drafter/release-drafter/releases/tag/v7.0.0)
