### ISSUE TITLE
Step does not fail on query failure

### ISSUE THREAD

**Issue by ozydingo** [release-drafter/release-drafter#1313]
Using `release-drafter/release-drafter@v5`

We encountered a failure in one of the internal steps of Draft Releaser. This failure caused our outputs to be empty, which breaks downstream steps. I expect this failure would cause the job to fail, but it did not.

To be clear, I am primarily concerned here that the job did not fail, and only secondarily concern with what the actual error was.

Log excerpt:

```
3playmedia-dev/threeplaymedia_app3: Found 42 releases
{ name: 'event', id: '4185073928' }
3playmedia-dev/threeplaymedia_app3: Draft release: 0.41.0
{ name: 'event', id: '4185073928' }
3playmedia-dev/threeplaymedia_app3: Last release: 0.40.0
{ name: 'event', id: '4185073928' }
3playmedia-dev/threeplaymedia_app3: Fetching parent commits of f76250b617f26cf72f50bb4af666f5a1fd93b060 since 2023-02-[14](https://github.com/3playmedia-dev/threeplaymedia_app3/actions/runs/4185073928/jobs/7252147220#step:2:15)T16:42:47Z
{ name: 'event', id: '4185073928' }
Error: Request failed due to following response errors:
 - Something went wrong while executing your query. Please include `5403:99CD:1CB71FC:3AB44D1:63ECF4EE` when reporting this issue.

...

Error: GraphqlResponseError: Request failed due to following response errors:
     - Something went wrong while executing your query. Please include `5403:99CD:1CB71FC:3AB44D1:63ECF4EE` when reporting this issue.
        at /home/runner/work/_actions/release-drafter/release-drafter/v5/dist/index.js:6088:13
        at async paginate (/home/runner/work/_actions/release-drafter/release-drafter/v5/dist/index.js:142845:14)
        at async findCommitsWithAssociatedPullRequests (/home/runner/work/_actions/release-drafter/release-drafter/v5/dist/index.js:142646:12)
        at async drafter (/home/runner/work/_actions/release-drafter/release-drafter/v5/dist/index.js:142388:7)
        at async Promise.all (index 0)

...

  stack: 'AggregateError: \n' +
    '    GraphqlResponseError: Request failed due to following response errors:\n' +
    '     - Something went wrong while executing your query. Please include `5403:99CD:1CB71FC:3AB44D1:63ECF4EE` when reporting this issue.\n' +
    '        at /home/runner/work/_actions/release-drafter/release-drafter/v5/dist/index.js:6088:13\n' +
    '        at async paginate (/home/runner/work/_actions/release-drafter/release-drafter/v5/dist/index.js:142845:14)\n' +
    '        at async findCommitsWithAssociatedPullRequests (/home/runner/work/_actions/release-drafter/release-drafter/v5/dist/index.js:142646:12)\n' +
    '        at async drafter (/home/runner/work/_actions/release-drafter/release-drafter/v5/dist/index.js:142388:7)\n' +
    '        at async Promise.all (index 0)\n' +
    '    at /home/runner/work/_actions/release-drafter/release-drafter/v5/dist/index.js:8826:19',
  type: 'Error'
```

For my own reference (private repo, this will not be accessible to others) https://github.com/3playmedia-dev/threeplaymedia_app3/actions/runs/4185073928/jobs/7252147220

**Comment by max-lobur** [comment]
Workaround:
```
      - name: Do release
        id: release
        uses: release-drafter/release-drafter@v5
...
      - name: Verify release
        if: steps.release.outputs.id == ''
        shell: bash
        run: exit 1
```

**Comment by mrfelton** [comment]
Also experiencing this. Errors from release drafter silently fail and do not cause a workflow error which masks problems and can created hard to debug errors in subsequent steps. Any error from release drafter should cause the step to fail with an error.

**Comment by cchanche** [comment]
About error handling, please see #1469

About your particular error, have you had the opportunity to reproduce @ozydingo ? If this is still ongoing, please provide reproduction (public) repository.
