### ISSUE TITLE
Deprecation: [@octokit/request-error] `error.code` is deprecated, use `error.status`.

### ISSUE THREAD

**Issue by tomasherman** [release-drafter/release-drafter#418]
Hi,

when using request-error, im getting following error:

```
Run release-drafter/release-drafter@v5.6.1
  env:
    JAVA_HOME: /opt/hostedtoolcache/jdk/8.0.242/x64
    JAVA_HOME_8.0.242_x64: /opt/hostedtoolcache/jdk/8.0.242/x64
    GITHUB_TOKEN: ***

08:45:53.238Z  INFO probot: avast/datadog4s: Found 26 releases
08:45:53.240Z  INFO probot: avast/datadog4s: No draft release found
08:45:53.240Z  INFO probot: avast/datadog4s: Last release: v0.6.3
08:45:53.240Z  INFO probot: avast/datadog4s: Fetching all commits for branch master since 2020-01-30T17:13:02Z
08:45:55.003Z  INFO probot: avast/datadog4s: Creating new draft release
Deprecation: [@octokit/request-error] `error.code` is deprecated, use `error.status`.
    at RequestError.get (/app/node_modules/@octokit/request/node_modules/@octokit/request-error/dist-node/index.js:29:17)
    at Object.Logger.stdSerializers.err (/app/node_modules/bunyan/lib/bunyan.js:1148:19)
    at /app/node_modules/bunyan/lib/bunyan.js:873:50
    at Array.forEach (<anonymous>)
    at Logger._applySerializers (/app/node_modules/bunyan/lib/bunyan.js:865:35)
    at mkRecord (/app/node_modules/bunyan/lib/bunyan.js:978:17)
    at Logger.error (/app/node_modules/bunyan/lib/bunyan.js:1044:19)
    at Application.<anonymous> (/app/node_modules/probot/lib/application.js:162:33)
    at step (/app/node_modules/probot/lib/application.js:44:23)
    at Object.throw (/app/node_modules/probot/lib/application.js:25:53)
    at rejected (/app/node_modules/probot/lib/application.js:17:65) {
  name: 'Deprecation'
}
08:45:55.119Z ERROR event: Not Found (id=e3236d23-d0ae-443a-bc52-f068c4036336)
  HttpError: Not Found
      at /app/node_modules/@octokit/request/dist-node/index.js:66:23
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

Any idea what am i doing wrong?

Thanks!

**Comment by casz** [comment]
The deprecation warning is just that a deprecation that's not the error message your interested in.

It's the second one your interested in
```
08:45:55.119Z ERROR event: Not Found (id=e3236d23-d0ae-443a-bc52-f068c4036336)
  HttpError: Not Found
      at /app/node_modules/@octokit/request/dist-node/index.js:66:23
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

However seems like you cut the stack trace off.

**Comment by tomasherman** [comment]
ah good to know - unfortunately that's all there is to the error:  https://github.com/avast/datadog4s/runs/435663429

**Comment by casz** [comment]
Looks off: https://github.com/avast/datadog4s/blob/master/.github/workflows/build.yml#L59

There is no need for a custom token. The default `secrets.GITHUB_TOKEN` that is provided by GitHub actions is good enough for drafting (as in you do not need to add a `GITHUB_TOKEN` secret)

**Comment by casz** [comment]
You can read more about here: https://help.github.com/en/actions/automating-your-workflow-with-github-actions/authenticating-with-the-github_token

**Comment by tomasherman** [comment]
Thanks! 

now it complains that signed token is missing :(

https://github.com/avast/datadog4s/runs/435722510?check_suite_focus=true

**Comment by casz** [comment]
Please see: https://github.com/release-drafter/release-drafter/blob/master/.github/workflows/release-drafter.yml
or read the example in the readme:
https://github.com/release-drafter/release-drafter/blob/master/README.md#L31-L32

**Comment by tomasherman** [comment]
oh now i understand - thanks i misunderstood your point in the first place ;)
