### ISSUE TITLE
ERROR event: Data doesn't contain `nodes` field.

### ISSUE THREAD

**Issue by ibuler** [release-drafter/release-drafter#578]
Work well before, but now error occur

Action url: https://github.com/ibuler/koko/runs/820944535
Error:  
```
Make sure the `paginatePath` is set to the field you wish to paginate and that the query includes the `nodes` field. 
(id=67d387bf-cb1c-4407-8d16-b062ecfd4dd9)   Error: Data doesn't contain `nodes` field. Make sure the `paginatePath` is 
set to the field you wish to paginate and that the query includes the `nodes` field.       at paginate (/app/lib/pagination.js:21:11)       at async module.exports.findCommitsWithAssociatedPullRequests (/app/lib/commits.js:88:12)  
     at async /app/index.js:40:9   --   event: {     "event": "push",     "id": "67d387bf-cb1c-4407-8d16-b062ecfd4dd9",     "repository": "ibuler/koko"   }
```

**Comment by timja** [comment]
Also hit this:

https://github.com/jenkinsci/theme-manager-plugin/runs/931054859?check_suite_focus=true

https://github.com/jenkinsci/theme-manager-plugin/blob/master/.github/workflows/release-drafter.yml

**Comment by calvarez-ov** [comment]
Any explanation/workaround? I just hit this 😢

**Comment by calvarez-ov** [comment]
In our case, a workaround is to use a simple tag instead of an annotated tag.
See #615
