### ISSUE TITLE
fail to run : error.code is deprecated

### ISSUE THREAD

**Issue by usk81** [release-drafter/release-drafter#626]
Error occurs when my release-drafter workflow runs.

```sh
Deprecation: [@octokit/request-error] `error.code` is deprecated, use `error.status`.
    at RequestError.get (/app/node_modules/@octokit/request/node_modules/@octokit/request-error/dist-node/index.js:29:17)
    at Object.Logger.stdSerializers.err (/app/node_modules/bunyan/lib/bunyan.js:1148:19)
    at /app/node_modules/bunyan/lib/bunyan.js:873:50
    at Array.forEach (<anonymous>)
    at Logger._applySerializers (/app/node_modules/bunyan/lib/bunyan.js:865:35)
    at mkRecord (/app/node_modules/bunyan/lib/bunyan.js:978:17)
    at Logger.error (/app/node_modules/bunyan/lib/bunyan.js:1044:19)
    at Application.<anonymous> (/app/node_modules/probot/lib/application.js:163:33)
    at step (/app/node_modules/probot/lib/application.js:44:23)
    at Object.throw (/app/node_modules/probot/lib/application.js:25:53)
    at rejected (/app/node_modules/probot/lib/application.js:17:65)
05:38:39.500Z ERROR event: Validation Failed: {"resource":"Release","code":"missing_field","field":"tag_name"}, {"resource":"Release","code":"custom","field":"tag_name","message":"tag_name is not well-formed"}, {"resource":"Release","code":"custom","message":"Published releases must have a valid tag"} (id=09c140ff-3b3f-4f1f-b6c6-1d15d1af2f1d)
  HttpError: Validation Failed: {"resource":"Release","code":"missing_field","field":"tag_name"}, {"resource":"Release","code":"custom","field":"tag_name","message":"tag_name is not well-formed"}, {"resource":"Release","code":"custom","message":"Published releases must have a valid tag"}
      at /app/node_modules/@octokit/request/dist-node/index.js:66:23
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by tk8817** [comment]
Also getting this. To add context, I see is on new repos which have no exisitng tags or releases

```
23:29:42.805Z  INFO probot:actions-workflows: Found 0 releases
23:29:42.807Z  INFO probot: actions-workflows: No draft release found
23:29:42.807Z  INFO probot: actions-workflows: No last release found
23:29:42.808Z  INFO probot: actions-workflows: Fetching all commits for reference refs/heads/master
23:29:43.701Z  INFO probot: actions-workflows: Creating new release
```

**Comment by marandaneto** [comment]
Almost the same, but:

09:41:02.640Z ERROR event: Validation Failed: {"resource":"Release","code":"invalid","field":"target_commitish"} (id=c51e18bb-9db6-4c35-a335-08ffc8a4d3e9)
  HttpError: Validation Failed: {"resource":"Release","code":"invalid","field":"target_commitish"}
      at /app/node_modules/@octokit/request/dist-node/index.js:66:23
      at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by sergeysova** [comment]
I have the same error: https://github.com/effector/patronum/runs/1173081059?check_suite_focus=true

**Comment by danvincenzi** [comment]
I have the same error:
  - https://github.com/dosedecafeine/terraform-google-network/runs/1214428863?check_suite_focus=true

**Comment by jetersen** [comment]
Try to delete the draft and run it again.

**Comment by sergeysova** [comment]
Nothing changed

**Comment by metrue** [comment]
I get same error:
```
04:06:03.551Z ERROR event: Validation Failed: {"resource":"Release","code":"missing_field","field":"tag_name"}, {"resource":"Release","code":"custom","field":"tag_name","message":"tag_name is not well-formed"}, {"resource":"Release","code":"custom","message":"Published releases must have a valid tag"} (id=df16136a-cb7d-4de6-8077-4e9ef6957572)
  HttpError: Validation Failed: {"resource":"Release","code":"missing_field","field":"tag_name"}, {"resource":"Release","code":"custom","field":"tag_name","message":"tag_name is not well-formed"}, {"resource":"Release","code":"custom","message":"Published releases must have a valid tag"}
      at /app/node_modules/@octokit/request/dist-node/index.js:66:23
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
  --
  event: {
    "event": "push",
    "id": "df16136a-cb7d-4de6-8077-4e9ef6957572",
    "repository": "gikiapp/sdk"
  }
```

**Comment by jetersen** [comment]
@metrue same as above: https://github.com/release-drafter/release-drafter/issues/626#issuecomment-704300078

**Comment by athackst** [comment]
FYI I didn't need to delete my draft. I was able to fix this by changing the release target from master to main inside the draft.

**Comment by jetersen** [comment]
I think the simple solution is to delete draft and try again.
